site_name: API DigitalPath
theme:
  name: material
  favicon: assets/digital.png
  logo: assets/digital.png
  
nav:
  - Home: 'index.md'
  - "API":
    - 'Correios': 'correios.md'
    - 'Receita': 'receita.md'
    - 'Sintegra': 'sintegra.md'

plugins:
    - mermaid2
